import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { blogs } from 'data/blogs'

type Post = {
  creator: string,
  title: string,
  link: string,
  pubDate: Date,
  ['content:encoded']: string,
  ['content:encodedSnippet']: string,
  isoDate: Date,
  content: string,
  contentSnippet: string
}

type ComponentProps = {
  posts: Post[]
}

export default function Home(props: ComponentProps) {

  const allBlogs = blogs.map((blog, i) => {
    return (
      <p key={i}>{blog.title}</p>
    )
  })

  const posts = props.posts;

  const allPosts = posts.map((post, i) => {
    return (
      <div key={i}><p >{post.title}</p><p>{post.contentSnippet}</p></div>
    )
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1>The Dataviz Corner</h1>
        {/* {allBlogs} */}
        {allPosts}
      </main>
    </>
  )
}

// Fetching data from the JSON file
import fsPromises from 'fs/promises';
import path from 'path'

export async function getStaticProps() {
  const filePath = path.join(process.cwd(), 'data/data.json');
  const jsonData = await fsPromises.readFile(filePath);
  const posts = JSON.parse(jsonData);

  return {
    props: {
      posts,
    },
  }
}
