name: "Fetch RSS Feeds"

# on:
#   schedule:
#     - cron: "*/5 * * * *"
on: push

jobs:
  fetch-blog-data:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v3
      # Run index.js in my root folder
      - name: Fetch RSS feeds and write JSON data
        uses: data/dist/index.js
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "fetch data"
          git push
