- name: RSS to JSON
  # You may pin to the exact commit or the version.
  # uses: I-Valchev/rss-to-json@e416c2cf938b8df9ec007a2f11ae2a80045c9589
  uses: I-Valchev/rss-to-json@1.0.0
  with:
    # The source directory and filename (incl. .yaml)
    source: # optional, default is feeds.yaml
    # The target directory and filename (incl. .json)
    target: # optional, default is feeds.json
    # Sort the feed items by a field. Default is isoDate.
    sortBy: # optional, default is isoDate
    # Specify the order direction. 'desc' or 'asc'. Default is desc.
    sortOrder: # optional, default is desc
